import type { ILocation } from './types/location';

export const locations: ILocation[] = [
  {
    id: '1',
    locationName: 'Bodø',
    temperature: 20,
    precipitation: 0,
    wind: 11,
    units: { temperature: '°', precipitation: 'mm', wind: 'm/s' },
  },
  {
    id: '2',
    locationName: 'Tromsø',
    temperature: 19,
    precipitation: 10,
    wind: 4,
    units: { temperature: '°', precipitation: 'mm', wind: 'm/s' },
  },
  {
    id: '3',
    locationName: 'Marienlyst',
    temperature: 15,
    precipitation: 12,
    wind: 3,
    units: { temperature: '°', precipitation: 'mm', wind: 'm/s' },
  },
  {
    id: '4',
    locationName: 'Nord',
    temperature: -3,
    precipitation: 0,
    wind: 2,
    units: { temperature: '°', precipitation: 'mm', wind: 'm/s' },
  },
  {
    id: '5',
    locationName: 'Longyearbyen',
    temperature: 9,
    precipitation: 0,
    wind: 4,
    units: { temperature: '°', precipitation: 'mm', wind: 'm/s' },
  },
  {
    id: '6',
    locationName: 'Trondheim',
    temperature: 24,
    precipitation: 3,
    wind: 4,
    units: { temperature: '°', precipitation: 'mm', wind: 'm/s' },
  },
  {
    id: '7',
    locationName: 'Kautokeino',
    temperature: 13,
    precipitation: 0,
    wind: 9,
    units: { temperature: '°', precipitation: 'mm', wind: 'm/s' },
  },
  {
    id: '8',
    locationName: 'Troll Antarktis',
    temperature: -35,
    precipitation: 0,
    wind: 6,
    units: { temperature: '°', precipitation: 'mm', wind: 'm/s' },
  },
];
